### ISSUE TITLE
LoRa RX/TX example doesn't receive data

### ISSUE THREAD

**Issue by sajanikapukotuwa** [BastilleResearch/gr-lora#23]
I complied the gr-LoRa project successfully by running the commands, 

```
git clone git://github.com/BastilleResearch/gr-lora.git
cd gr-lora
mkdir build
cd build
cmake ../
make
sudo make install
sudo ldconfig
```
I am using USRP N210 device with compatible daughter-board from which I have already viewed a LoRa chirp using GNU/Radio spectrogram. 

After successfully compiling the gr-LoRa project and prior to opening the txrz_usrp.grc example I  opened a UDP netcat server so that the socket PDU on port 52002 would safety connect. On the other terminal I had a UDP client running on port 52001.  However, although I keep writing to the UDP 52001 socket, I get nothing on the other socket (52002). My settings are described below.

![image](https://user-images.githubusercontent.com/20855805/33127714-a4e85432-cfc4-11e7-9268-8f2803e36b50.png)

Observations: 
All I see is a 'U' in the debug output in GNU Radio terminal for every character I send to  UDP socket 52001 through my client. I also see the LED light B blinking for every character I send through UDP client.

My netcat terminals if required are below,

![image](https://user-images.githubusercontent.com/20855805/33127890-591bf6b6-cfc5-11e7-9e78-6e10080f8baf.png)

![image](https://user-images.githubusercontent.com/20855805/33127895-5ca11cee-cfc5-11e7-9b39-cd5d4583e81e.png)

I would so much grateful if someone can help me rectify this error.

**Comment by brunoricardojava** [comment]
@sajanikapukotuwa  I'm with the same problem, did you find a solution?
