### ISSUE TITLE
about the gray coding

### ISSUE THREAD

**Issue by orkfire** [BastilleResearch/gr-lora#26]
Hi @matt-knight I've been reading your ppt and watch the video, I have read all the program of the gr-lora, because i don't have the usrp board, i use ad9364 instead, i have demod the lora signal, but when dealing with decode, I am confused, why use to_gray()  in the decode program, other than using from_gray().
thanks!!!

**Comment by matt-knight** [comment]
Hi @orkfire, `to_gray()` is used because that is what I discovered to be the empirical solution during the course of my reverse engineering effort.  I know it's confusing -- I don't have a great answer for you beyond that's what works in practice :)

Hope this helps,
Matt
