### ISSUE TITLE
Source - out(0): Port is not connected.

### ISSUE THREAD

**Issue by zoutepopcorn** [BastilleResearch/gr-lora#6]
i'm a noob in using GNU radio.

I've some red blocks:
- pfb_arb_resampler
- 2x Missing block key lorademod

It said: Source - out(0):

Trying to connect an rtl2832 (dvb-t) stick to it. Any solutions?

Thanks for the cool work

**Comment by matt-knight** [comment]
Thanks for your interest!  Please begin by verifying that you've installed GNU Radio and `gr-lora` on your system, and that your installation destinations are in your path.  `pfb_arb_resampler` is within the core GNU Radio package, and the LoRa package is included in `gr-lora`.  There are many guidelines on how to install GNU Radio for various OSes, including the official reference: http://gnuradio.org/redmine/projects/gnuradio/wiki/InstallingGR

**Comment by matt-knight** [comment]
I'm going to mark this closed due to inactivity for now.  Feel free to re-open or create a new issue if you are still having trouble.  Thanks!

**Comment by zoutepopcorn** [comment]
Okido Thanks for your info
